### ISSUE TITLE
FHIRcast needs a logotype

### ISSUE THREAD

**Issue by lbergnehr** [HL7/fhircast-docs#20]
It would be great for many places: fhircast.org, the GitHub profile, etc. A few conceptual ideas to start with:

1. A hand holding a fire (fhir?) flame.
2. Two hands holding a fire (fhir?) flame together. They're *in sync*.
3. A fhir flame broadcasting (typical broadcast symbol or something like that).

🔥

**Comment by NiklasSvenzen** [comment]
Agree

**Comment by isaacvetter** [comment]
Also note that mkdocs specifically supports [favicon](http://www.mkdocs.org/user-guide/styling-your-docs/), which would be another great place for this logo.

**Comment by andli** [comment]
I took a shot at it:
![Logo](https://i.imgur.com/TzzI98q.png)

And how it looks on dark background:
![Logo-dark](https://i.imgur.com/X61CWhP.png)
