### ISSUE TITLE
Dial-in for WG meetings and resources?

### ISSUE THREAD

**Issue by jeremysrichardson** [HL7/fhircast-docs#262]
I saw a message at one point saying there was a WG meeting on 7/17, but it's very difficult to discover through FHIRCast.org.  It would be great to get a link on FHIRCast.org to upcoming meetings and meeting minutes.

If there's a meeting today, can someone post info here?

**Comment by wmaethner** [comment]
[https://confluence.hl7.org/display/IMIN/2019-07-17+FHIRcast](url)

**Comment by jeremysrichardson** [comment]
Thanks @wmaethner !

**Comment by jeremysrichardson** [comment]
What would be the process to get that link into the FHIRCast.org front page?

**Comment by ajuliansr** [comment]
According to the Decision Making Practices of the HL7 InM work group, conference calls are posted on the HL7 website conference call tool.
Go to https://www.hl7.org/concalls/Default.aspx?ref=nav then from the drop-down select Infrastructure And Messaging.

**Comment by ajuliansr** [comment]
According to the Decision Making Practices of the HL7 InM work group, conference calls are posted on the HL7 website conference call tool.
Go to https://www.hl7.org/concalls/Default.aspx?ref=nav then from the drop-down select Infrastructure And Messaging.
