### ISSUE TITLE
Close events don't contain context

### ISSUE THREAD

**Issue by wmaethner** [HL7/fhircast-docs#69]
The closing events currently don't have any context specified, but it seems useful to know the context of what specifically is being closed. This would be extremely useful in the case of unidirectional integration syncing. For example a subscribing app receives the notifications for an open study and puts that in focus. They are not implementing bi-directional syncing and the user then opens a different study in the subscribing application. The driving application then closes the original study. The current spec would dictate that the subscribing app close the current study or both studies, either of which I don't think is necessarily what we want. If they only close the in focus study (study B) then the original study is still open in the subscribing application even though it was closed in the driving application which seems clearly wrong. If they close both then that could annoy the user who wanted to keep in focus that manually opened study. 

This has caused some issues with current integrations where some systems don't pay attention to the context of the close and will instead just close everything or the current thing which can cause some weird behavior.

**Comment by isaacvetter** [comment]
Makes sense to me, but I'll defer to ya'll's experienced opinion. 
@bvdh also made this point during the Jan WGM.

**Comment by NiklasSvenzen** [comment]
Yes, I agree. This is true for both close and logout events, where it makes sense to include the context of the closed or logged out item.

**Comment by bvdh** [comment]
This also makes sense from another perspective. There is an issue if two applications want the close the chart at the same time.  This will result in closing two charts. The current and the next one.
So yes, the context should be included.

**Comment by isaacvetter** [comment]
Fixed in #76 . Closing.
